### ISSUE TITLE
The same result on a status command every time

### ISSUE THREAD

**Issue by MariaPaypoint** [MinterTeam/minter-explorer-api#102]
I use explorer-api as a docker container. 

I noticed such a strange thing: when I do a manual request to explorer-api container, I get the same result every time (in a field "latest_block_height"):
```
# wget http://explorer-api:8080/api/v2/status -O -
{"data":{"avg_block_time":62.98202425790966,"bip_price_change":0,"bip_price_usd":0,"latest_block_height":17246,"latest_block_time":"2020-10-22T09:42:05+03:00","market_cap":0,"total_transactions":0,"transactions_per_second":0}}

# wget http://explorer-api:8080/api/v2/status -O -
{"data":{"avg_block_time":62.98202425790966,"bip_price_change":0,"bip_price_usd":0,"latest_block_height":17246,"latest_block_time":"2020-10-22T09:42:05+03:00","market_cap":0,"total_transactions":0,"transactions_per_second":0}}

# wget http://explorer-api:8080/api/v2/status -O -
{"data":{"avg_block_time":62.98202425790966,"bip_price_change":0,"bip_price_usd":0,"latest_block_height":17246,"latest_block_time":"2020-10-22T09:42:05+03:00","market_cap":0,"total_transactions":0,"transactions_per_second":0}}
```

In postgres-database data is actual (I use explorer-extender project), new blocks create every 3 secs and show in table "blocks" - everithing is okay. I see in the database new data, but I see slightly outdated data as a response on a status command.

If I restart docker container, I start to receive another result, but it also the same every time:
```
# docker stop explorer-api
# docker start explorer-api

# wget http://explorer-api:8080/api/v2/status -O -
{"data":{"avg_block_time":62.28845631164105,"bip_price_change":0,"bip_price_usd":0,"latest_block_height":17452,"latest_block_time":"2020-10-22T09:56:35+03:00","market_cap":0,"total_transactions":0,"transactions_per_second":0}}

# wget http://explorer-api:8080/api/v2/status -O -
{"data":{"avg_block_time":62.28845631164105,"bip_price_change":0,"bip_price_usd":0,"latest_block_height":17452,"latest_block_time":"2020-10-22T09:56:35+03:00","market_cap":0,"total_transactions":0,"transactions_per_second":0}}
```

api version: 2.0.4

**Comment by GrKamil** [comment]
This is because of the cache in memory. Some data is going from the cache and updated just when a new block is received by WebSocket (centrifugo).  
You need to set the right values for the next env variables:
`CENTRIFUGO_LINK=wss://exporer-rtm.minter.network/connection/websocket`
`CENTRIFUGO_BLOCK_CHANNEL=blocks`

**Comment by MariaPaypoint** [comment]
Thank you, the problem was in the centrifugo module.

Also I found that you are not using token authentication in the centrifugo. So, after configuring `config.json` in centrifugo, everything is fine. An example of a config file:

```
{
  "v3_use_offset": true,
  "token_hmac_secret_key": "token_hmac_secret_key",
  "api_key": "api_key",
  "admin_password": "admin_password",
  "admin_secret": "admin_secret",
  "client_anonymous": true,
  "anonymous": true
}
```
