### ISSUE TITLE
Set order Order("time_id DESC") 

### ISSUE THREAD

**Issue by EvgeniyTaburyanskiy** [MinterTeam/minter-explorer-api#90]
https://github.com/MinterTeam/minter-explorer-api/blob/eaa18d773f1c025b6b1281dcd2f191b241dbe25f/reward/repository.go#L75

Please set order Order("time_id DESC"). like in method  GetPaginatedAggregatedByAddress

**Comment by GrKamil** [comment]
It will be added in the next explorer release.
